### ISSUE TITLE
Can't search Notion with Flow Launcher plugin

### ISSUE THREAD

**Issue by obkommy** [MinYn/flow-launcher-notion-plugin#3]
[Eagan Log File 2024-01-16.txt](https://github.com/MinYn/flow-launcher-notion-plugin/files/13951516/Eagan.Log.File.2024-01-16.txt)

Flow Launcher version: 1.16.2
OS Version: 22631.3007
IntPtr Length: 8
x64: True

Python Path: C:\Users\eagan\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 01/16/2024 08:27:57
Exception:
Notion Search Exception: 
Websites: https://github.com/MinYn/flow-launcher-notion-plugin
Author: MinYn
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\eagan\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.1\run.py", line 3, in <module>
    import i18n
ModuleNotFoundError: No module named 'i18n'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\eagan\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.1\run.py", line 3, in <module>
    import i18n
ModuleNotFoundError: No module named 'i18n'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MinYn** [comment]
@obkommy this issue resolved! please remove and install.

resolve below url
https://github.com/MinYn/flow-launcher-notion-plugin/compare/ca2f4d35c3d8ebf4c3e0f88cab644c2539604286...4d9cee72c8cf822c711cad4204676848b7a6bd05
