### ISSUE TITLE
Error on query

### ISSUE THREAD

**Issue by DBradleyRI** [MinYn/flow-launcher-notion-plugin#4]
The log file is attached and sharing the exception message below. 
[2024-01-16.txt](https://github.com/MinYn/flow-launcher-notion-plugin/files/13953968/2024-01-16.txt)
I just installed it with the API (not set to public as that didn't seem necessary?):

Flow Launcher version: 1.16.2
OS Version: 22631.3007
IntPtr Length: 8
x64: True

Python Path: C:\Users\David\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 01/16/2024 12:42:36
Exception:
Notion Search Exception: 
Websites: https://github.com/MinYn/flow-launcher-notion-plugin
Author: MinYn
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\David\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.1\run.py", line 15, in <module>
    from plugin.main import Query
  File "C:\Users\David\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.1\plugin\main.py", line 2, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\David\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.1\run.py", line 15, in <module>
    from plugin.main import Query
  File "C:\Users\David\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.1\plugin\main.py", line 2, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by MinYn** [comment]
@DBradleyRI Maybe Error resolved Next Version(v1.0.2)

ref)
https://github.com/MinYn/flow-launcher-notion-plugin/pull/5
