### ISSUE TITLE
Error when testing ns for the first time

### ISSUE THREAD

**Issue by Chaoscontrol** [MinYn/flow-launcher-notion-plugin#7]
No clue what I did wrong. 

[2024-01-26.txt](https://github.com/MinYn/flow-launcher-notion-plugin/files/14069240/2024-01-26.txt)
```
Flow Launcher version: 1.16.2
OS Version: 22621.3007
IntPtr Length: 8
x64: True

Python Path: C:\Users\axdr\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 01/26/2024 20:42:47
Exception:
Notion Search Exception: 
Websites: https://github.com/MinYn/flow-launcher-notion-plugin
Author: MinYn
Version: 1.0.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\axdr\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.3\run.py:24: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
  loc = locale.getdefaultlocale()[0]

 ---> System.IO.InvalidDataException: C:\Users\axdr\AppData\Roaming\FlowLauncher\Plugins\Notion Search-1.0.3\run.py:24: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
  loc = locale.getdefaultlocale()[0]

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ```

**Comment by nuexq** [comment]
the same bro

**Comment by MinYn** [comment]
I'll check and write back here, thanks for reporting the error.
@Chaoscontrol @No0ne003

**Comment by MinYn** [comment]
@Chaoscontrol @No0ne003 please update next v1.0.4 version maybe this error not showing.

**Comment by Chaoscontrol** [comment]
> @Chaoscontrol @No0ne003 please update next v1.0.4 version maybe this error not showing.

Sorry, I'm a new user. Can I manually update? New version doesn't show in the plugin store yet, even refreshing.

**Comment by nuexq** [comment]
> > @Chaoscontrol @No0ne003 please update next v1.0.4 version maybe this error not showing.
> 
> Sorry, I'm a new user. Can I manually update? New version doesn't show in the plugin store yet, even refreshing.

install the version and put it on:
 C:\Users\{userName}\Downloads\app\FlowLauncher\app-1.16.2\UserData\Plugins
and rename the pulgin with the version

**Comment by Chaoscontrol** [comment]
> > > @Chaoscontrol @No0ne003 please update next v1.0.4 version maybe this error not showing.
> > 
> > 
> > Sorry, I'm a new user. Can I manually update? New version doesn't show in the plugin store yet, even refreshing.
> 
> install the version and put it on: C:\Users{userName}\Downloads\app\FlowLauncher\app-1.16.2\UserData\Plugins and rename the pulgin with the version

Np, I got help on Discord. You can just do 
`pm install  <URL to zip>` 
It worked, and now it's working fine. Thanks!
